HOST = '11.111.111.11'
PORT = '3306'
DB_DATABASE = 'yourdatabase'
DB_USERNAME = 'your_user'
DB_PASSWORD = 'your_password'

SQLALCHEMY_DATABASE_URI = f'mysql+pymysql://{DB_USERNAME}:{DB_PASSWORD}@{HOST}:{PORT}/{DB_DATABASE}'
SQLALCHEMY_TRACK_MODIFICATIONS = False
